In [34]:
# Numerics
import numpy as np



In [35]:
arr=np.empty((3,2,2))

In [40]:
arr[:,0,0]=

array([4.67087019e-310, 0.00000000e+000, 0.00000000e+000])

In [48]:

list1=np.array([1,2,3])
list2=np.array([4,5,6])
list3=np.array([7,8,9])
list4=np.array([10,11,12])

In [41]:
for row in range(2):
    for col in range(2):
        arr[:,row,col]=list1


In [49]:
arr[:,0,0]=list1
arr[:,0,1]=list2
arr[:,1,0]=list3
arr[:,1,1]=list4

In [50]:
arr

array([[[ 1.,  4.],
        [ 7., 10.]],

       [[ 2.,  5.],
        [ 8., 11.]],

       [[ 3.,  6.],
        [ 9., 12.]]])

In [4]:
Alist=np.dstack([list1,list2,list3,list4]).reshape(3,2,2)
Mlist=np.array(list((map(np.asmatrix,Alist))))
type(Mlist[1])

numpy.ndarray

In [6]:
Alist

array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]])

In [38]:
tupple(map(lambda x:x,{1,2,3})

In [21]:
np.asmatrix(Alist[0])

matrix([[ 1,  4],
        [ 7, 10]])

In [32]:
map(np.asmatrix,Alist)

In [31]:
arr=[[[0 for i in range(2)] for j in range(2)]for k in range(3)]

In [33]:
np.empty

[[0, 0], [0, 0]]

In [11]:
[[0]*2 for i in range(2)]


[[0, 0], [0, 0]]

In [51]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
list4=[10,11,12]

In [63]:
np.dstack([list1,list2])[0,0]

array([1, 4])

In [60]:
np.stack([list1,list2])[0]

array([1, 2, 3])

In [61]:
np.hstack([list1,list2])[0]

1

In [65]:
np.column_stack([list1,list2])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
np.array(list1)@np.array(list1)

14

In [80]:
np.linalg.inv([np.column_stack(([1,1],[-1,1])),np.column_stack(([1,1],[-1,1]))])

array([[[ 0.5,  0.5],
        [-0.5,  0.5]],

       [[ 0.5,  0.5],
        [-0.5,  0.5]]])

In [84]:
np.array([[1,2],[3,4]])@np.column_stack([[1,0],[0,1],[2,0]])

array([[1, 2, 2],
       [3, 4, 6]])

In [91]:
np.dstack([[[1],[0]],[[0],[1]],[[2],[0]]])

array([[[1, 0, 2]],

       [[0, 1, 0]]])

In [94]:
[0]+[i for i in range(3)]

[0, 0, 1, 2]