In [3]:
from __future__ import unicode_literals, print_function, division

import numpy as np
import scipy.integrate as integrate

from scipy import constants
from scipy import interpolate

_GN_ = constants.gravitational_constant # Meter^3 Kilogram^-1 Second^-2 
_c_light_ = constants.c # Meter Second^-1
_eV_ = constants.eV; # Meter^2 Kilogram Second^-2
_kB_ = constants.Boltzmann # Joule Kelvin^-1
_hP_ = constants.Planck # Joule Second 
_aB_ = 8*np.pi**5*_kB_**4/(15*_hP_**3*_c_light_**3) #Joule Kelvin^-4 Meter-3

In [4]:
Tcmb0 = 2.7255 # Kelvin 
Nur0 = 3.046;
h0 = 0.67556;
Omega_b0 = 0.022032;
Omega_cdm0 = 0.12038;
defaultParm = {"T":Tcmb0, 'Nur':Nur0,'h':h0, 'Omega_b':Omega_b0, 'Omega_cdm': Omega_cdm0};

In [6]:


class cosmic_fluid(object):
    """A fluid model for cosmic material
    
        naught values corrispond to today
        
        """
    pass
        
class cosmic_fluid_const_w(cosmic_fluid):
    """A cosmic fluid with constant w(a)"""
    
    def __init__(self,rho_ref,w,a_0=1.,a_ref=1.):
        self.w = lambda a=a_0: w
        self.a_0 = a_0
        self.rho_0 = rho_ref * (a_ref/a_0)**(3*(1+w))
        
    def rho(self,a):
        return self.rho_0*(self.a_0/a)**(3*(1+ self.w()))
    
    def p(self,a):
        return self.rho(a) * self.w(a)
    
class cosmic_fluid_spline_w(cosmic_fluid):
    """A cosmic fluid with a given spline made with numpy.interpolate.splrep for w(a)"""
    
    def __init__(self,rho_ref,w_splinerep,a_0=1.,a_ref=1.):
        self.w_spline_rep = w_splinerep
        self.w = lambda a:interpolate.splev(np.log10(a), w_splinerep, der=0)
        self.a_0 = a_0
        self.rho_0 = rho_ref * (a_ref/a_0)**3* 10**(-3*interpolate.splint(np.log10(a_ref),np.log10(a_0),w_gamma_spline_rep))
        
    def rho(self,a):
        return self.rho_0*(self.a_0/a)**3 * 10**(-3*interpolate.splint(np.log10(self.a_0),np.log10(a),w_gamma_spline_rep))
    
    def p(self,a):
        return self.rho(a) * self.w(a)
    
    
def rho_0_gamma(T=Tcmb0):
    return _aB_ / _c_light_**2 * T**4
    
def w_gamma(a):
    return 1./3.

log10a_range= np.arange(-14.5,0.5,0.1)
vw=np.vectorize(w_gamma)
vw(log10a_range)
w_gamma_spline_rep=interpolate.splrep(log10a_range, vw(log10a_range), s=0)

gamma_spl = cosmic_fluid_spline_w(rho_0_gamma(),w_gamma_spline_rep,a_ref=1/2)
gamma= cosmic_fluid_const_w(rho_0_gamma(),1/3)

In [26]:
def w_gamma(loga):
    return 1/3

integrate.quad(w_gamma, 0, 5)

(1.666666666666667, 1.8503717077085944e-14)

In [173]:
test = gamma_spl.w(10**-6)
test

array(0.33333333)

In [13]:
np.array(-15,-5,-4.6,-4.2,-3.8,-3.4,-3,0)




array([-20. , -19.6, -19.2, -18.8, -18.4, -18. ])

In [171]:
w_gamma_spline_rep=interpolate.splrep(log10a_range, vw(log10a_range), s=0)
interpolate.splev(log10a_range, w_gamma_spline_rep, der=0)
interpolate.splint(1,1,w_gamma_spline_rep)

0.0

In [132]:
vw(log10a_range)

array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333

In [87]:
np.arange(-15,1,0.5)

array([-15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5, -11. ,
       -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,
        -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,
        -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [2]:
rho_0['crit', opts : OptionsPattern[]] = ((3  H0[opts]^2)/(
   8 \[Pi] GN));
\[Rho]0[\[Gamma], OptionsPattern[]] = 
  aB/c\[Gamma]^2*OptionValue[T]^4;
\[Rho]0[\[Nu], 
   opts : OptionsPattern[]] = \[Rho]0[\[Gamma], opts]*7/
    8*(4/11)^(4/3)*OptionValue[Nur];
\[Rho]0[r, 
   opts : OptionsPattern[]] = \[Rho]0[\[Gamma], opts] + \[Rho]0[\[Nu],
     opts];
\[Rho]0[b, opts : OptionsPattern[]] = 
  OptionValue[\[Omega]b] \[Rho]0[crit, opts]/OptionValue[h]^2;
\[Rho]0[cdm, opts : OptionsPattern[]] = 
  OptionValue[\[Omega]cdm] \[Rho]0[crit, opts]/OptionValue[h]^2;
\[Rho]0[m, 
   opts : OptionsPattern[]] = \[Rho]0[b, opts] + \[Rho]0[cdm, opts];
\[Rho]0[bg, 
   opts : OptionsPattern[]] = \[Rho]0[m, opts] + \[Rho]0[r, opts];

\[Rho]0[\[CapitalLambda], 
   opts : OptionsPattern[]] = \[Rho]0[crit, opts] - \[Rho]0[bg, opts];

\[Rho]0[general_, opts : OptionsPattern[]] = \[Rho][general, opts][1];

Options[\[CapitalOmega]] = defaultParm;
\[CapitalOmega][MaterialIndex_, 
   opts : OptionsPattern[]] = \[Rho]0[MaterialIndex, opts]/\[Rho]0[
    crit, opts];


Options[\[Omega]0] = defaultParm;
\[Omega]0[MaterialIndex_, 
   opts : OptionsPattern[]] = \[CapitalOmega][MaterialIndex, 
    opts] OptionValue[h]^2;

conWMaterialIndex = {\[Gamma], \[Nu], r, b, cdm, 
   m, \[CapitalLambda]};
w[\[Gamma]][a_] = 1/3;
w[\[Nu]][a_] = 1/3;
w[r][a_] = 1/3;
w[b][a_] = 0;
w[cdm][a_] = 0;
w[m][a_] = 0;
w[\[CapitalLambda]][a_] = -1;


Options[\[Rho]] = defaultParm;
\[Rho][MaterialIndex_?(MemberQ[conWMaterialIndex, #] &), 
    opts : OptionsPattern[]][
   a_] = \[Rho]0[MaterialIndex, opts] a^(-3 (1 + w[MaterialIndex][a]));
\[Rho][bg, opts : OptionsPattern[]][
   a_] = \[Rho]0[m, opts] a^(-3 (1 + w[m][a])) + \[Rho]0[r, 
     opts] a^(-3 (1 + w[r][a]));

Options[\[Omega]] = defaultParm;
\[Omega][MaterialIndex_?(MemberQ[conWMaterialIndex, #] &), 
    opts : OptionsPattern[]][
   a_] = \[Omega]0[MaterialIndex, 
    opts] a^(-3 (1 + w[MaterialIndex][a]));


w[bg][a_] = (
   w[r][a] \[Rho][r][a] + w[m][a] \[Rho][m][a])/\[Rho][bg][a] // 
   FullSimplify;

In [14]:
def foo(**defaultParm):
        T

In [9]:
defaultParm['T']

2.7255

In [15]:
foo()

NameError: global name 'T' is not defined